const PDFDocument = require('pdfkit');

function generateInspectionPDF(inspection, res) {
  const doc = new PDFDocument({ margin: 50 });

  // Response ko seedha stream kar rahe hain - file disk pe save
  // karne ki zaroorat nahi, browser ko directly bhej rahe hain
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=inspection-${inspection._id}.pdf`
  );
  doc.pipe(res);

  // ---------- HEADER ----------
  doc
    .fontSize(20)
    .fillColor('#162447')
    .text('LegalMetrix AI', { align: 'left' })
    .fontSize(11)
    .fillColor('#5B6478')
    .text('Legal Metrology Inspection Report', { align: 'left' });

  doc.moveDown(1);
  doc
    .strokeColor('#D8DCE3')
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();
  doc.moveDown(1);

  // ---------- INSPECTION INFO ----------
  doc.fillColor('#1F2A44').fontSize(11);
  doc.text(`Inspection ID: ${inspection._id}`);
  doc.text(`Date: ${new Date(inspection.createdAt).toLocaleString()}`);
  doc.text(`Officer: ${inspection.officer?.name || 'N/A'}`);
  doc.moveDown(1);

  // ---------- PRODUCT INFO ----------
  doc.fontSize(14).fillColor('#162447').text('Product Information');
  doc.fontSize(11).fillColor('#1F2A44');
  doc.text(`Product Name: ${inspection.productName}`);

  const fields = inspection.extractedData || {};
  Object.keys(fields).forEach((key) => {
    if (key === 'confidence') return; // confidence ko alag se treat karenge, yahan skip
    doc.text(`${formatLabel(key)}: ${fields[key] || 'Not found'}`);
  });
  doc.moveDown(1);

  // ---------- COMPLIANCE STATUS ----------
  doc.fontSize(14).fillColor('#162447').text('Compliance Status');
  const statusColor =
    inspection.status === 'pass' ? '#3B6D11' : inspection.status === 'fail' ? '#A32D2D' : '#B5720F';

  doc
    .fontSize(16)
    .fillColor(statusColor)
    .text(`${inspection.status.toUpperCase()}  —  ${inspection.complianceScore}%`);
  doc.moveDown(1);

  // ---------- VIOLATIONS ----------
  doc.fontSize(14).fillColor('#162447').text('Violations');
  doc.fontSize(11).fillColor('#1F2A44');

  if (!inspection.violations || inspection.violations.length === 0) {
    doc.fillColor('#3B6D11').text('No violations found.');
  } else {
    inspection.violations.forEach((v, i) => {
      doc
        .fillColor('#A32D2D')
        .text(`${i + 1}. ${v.message} (Severity: ${v.severity})`);
    });
  }
  doc.moveDown(1);

  // ---------- SEIZURE MEMO ----------
  if (inspection.seizureMemo?.samplesSeized != null) {
    doc.fontSize(14).fillColor('#162447').text('Seizure Memo');
    doc.fontSize(11).fillColor('#1F2A44');
    doc.text(`Samples Seized: ${inspection.seizureMemo.samplesSeized}`);
    doc.text(`Samples Released: ${inspection.seizureMemo.samplesReleased}`);
    doc.text(`Disposal Note: ${inspection.seizureMemo.disposalNote}`);
    if (inspection.seizureMemo.reasonsToBelieve) {
      doc.text(`Reasons to Believe: ${inspection.seizureMemo.reasonsToBelieve}`);
    }
    doc.moveDown(1);
  }

  // ---------- FOOTER ----------
  doc
    .fontSize(9)
    .fillColor('#5B6478')
    .text('Generated by LegalMetrix AI — Automated Compliance Inspection Platform', 50, 750, {
      align: 'center',
    });

  doc.end(); // isse PDF finalize hoti hai aur stream complete hota hai
}

function formatLabel(field) {
  const result = field.replace(/([A-Z])/g, ' $1');
  return result.charAt(0).toUpperCase() + result.slice(1);
}

module.exports = { generateInspectionPDF };